# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'
# ignore all warnings from all dependencies
inhibit_all_warnings!

target 'BLT' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BLT
  pod 'SwiftLint'
  pod 'RandomColorSwift'

  target 'BLTTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BLTUITests' do
    # Pods for testing
  end

end
