platform :ios, '12.1'
use_frameworks!

target 'BLT' do
  pod 'Charts', '~> 3.2.2'
  pod 'SwiftReorder', '~> 6.0.2'
  pod 'DropDown', '2.3.4'
  pod 'RandomColorSwift'
  pod 'SwiftLint'
  pod 'LBConfettiView'
  pod 'Datez'
  pod 'VerticalCardSwiper'
  pod 'RetroProgress'
  pod 'RealmSwift', '~> 4.3.2'
  pod 'gooey-cell'
  pod 'TimelineCards'
end

