# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(workspace: "BLT.xcworkspace", scheme: "BLT Screenshots")
    sh("brew", "install", "imagemagick")
    frame_screenshots(path: "../docs/screenshots")
  end
  desc "Create A Beta Build"
  lane :beta do
    xcversion(version: "10.1") # Selects Xcode 10.1
    match(type: "development", readonly: is_ci)
    build_app(scheme: "BLT", workspace: "BLT.xcworkspace", export_method: "development")
  end
  desc "Resets All Certifications And Regens Them"
  lane :regencerts do
    match nuke development
    match nuke distribution
    match nuke appstore
    match(type: "development")
    match(type: "distribution")
    match(type: "appstore")
  end
  desc "Generate Jazzy Documentation"
  lane :documentation do
    xcode_select("/Applications/Xcode_10.3.app")
    puts(sh("swiftc", "--version"))
    jazzy(config:".jazzy.yaml")
  end
end
