# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
# devices([
#   "iPhone XR",
#   "iPhone 8",
#   "iPhone 8 Plus",
#   "iPhone X"
# ])
devices([
    "iPhone 8"
])

languages([
  "en-US"
])

# The name of the scheme which contains the UI Tests
scheme("BLT Screenshots")

# Where should the resulting screenshots be stored?
output_directory("../docs/screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Remove the '#' to set the status bar to 9:41 AM, and show full battery and reception.
override_status_bar(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
launch_arguments(["-HasOnboarded true -IsTesting true"])

# For more information about all available options run
# fastlane action snapshot
